server:
  port: 9001
page:
  size: 5


#mysql驱动
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis:
#实体类别名
  type-aliases-package: com.lanou.entity
#映射文件地址
  mapper-locations: classpath:mappers/*.xml

#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.lanou.util.MyMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql